services:
  app:
    build: .
    ports:
      - "8080:${PORT:-3000}"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      YT_API_KEY: ${YT_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      S3_BUCKET: ${S3_BUCKET}
      DDB_TABLE_FILES: ${DDB_TABLE_FILES}
      DDB_TABLE_JOBS: ${DDB_TABLE_JOBS}
      COGNITO_REGION: ap-southeast-2
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET} 

      # >>> AWS SDK needs these <<<
      AWS_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      # AWS_PROFILE: CAB432-STUDENT-901444280953        # <-- your SSO profile name
      # AWS_SDK_LOAD_CONFIG: "1"
    volumes:
      - ./data:/app/data
      - ./public:/app/public:ro

      # Windows path to your AWS folder (pick ONE of the two lines below)
      - "C:\\Users\\Tech\\.aws:/root/.aws"    # Windows-style path (escape backslashes)
      # - "/c/Users/Tech/.aws:/root/.aws:ro"     # Git Bash style (alternative)

    depends_on:
      mariadb:
        condition: service_started
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  dbdata:
